apiVersion: apps/v1
kind: Deployment

metadata:
  name: cortiva-backend
  namespace: cortiva
  labels:
    app: cortiva-backend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cortiva-backend

  template:
    metadata:
      labels:
        app: cortiva-backend

    spec:
      containers:
        - name: cortiva-backend
          image: yashwanthvenaganti/cortiva-backend:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: cortiva-config

            - secretRef:
                name: cortiva-secret

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5