apiVersion: v1
kind: Secret
metadata:
  name: cortiva-secret
  namespace: cortiva

type: Opaque

stringData:
  DB_USERNAME: "admin"
  DB_PASSWORD: "Yashwanth"

  JWT_SECRET: "YOUR_JWT_SECRET"

  MAIL_USER: "YOUR_GMAIL@gmail.com"
  MAIL_PASS: "YOUR_GMAIL_APP_PASSWORD"

  AWS_ACCESS_KEY_ID: "YOUR_AWS_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "YOUR_AWS_SECRET_ACCESS_KEY"
