apiVersion: v1
kind: Secret

metadata:
  name: cortiva-secret
  namespace: cortiva

type: Opaque

data:
  DB_USERNAME: <base64>
  DB_PASSWORD: <base64>

  JWT_SECRET: <base64>

  EMAIL_USER: <base64>
  EMAIL_PASSWORD: <base64>

  AWS_ACCESS_KEY_ID: <base64>
  AWS_SECRET_ACCESS_KEY: <base64>