apiVersion: v1
kind: Secret
metadata:
  name: cortiva-secret
  namespace: cortiva

type: Opaque

stringData:
  DB_USER: "<DB_USERNAME>"
  DB_PASSWORD: "<DB_PASSWORD>"

  JWT_SECRET: "<JWT_SECRET>"

  MAIL_USER: "<MAIL_USER>"
  MAIL_PASS: "<MAIL_APP_PASSWORD>"

  AWS_ACCESS_KEY_ID: "<AWS_ACCESS_KEY_ID>"
  AWS_SECRET_ACCESS_KEY: "<AWS_SECRET_ACCESS_KEY>"